<script src="<?php echo $this->baseUrl().'/static/js/index/index.js' ?>">
</script>
<script src="<?php echo $this->baseUrl().'/static/js/bootstrap-datepicker.js' ?>">
</script>
<link type="text/css" rel="stylesheet" media="screen" href="<?php echo $this->baseUrl().'/static/css/datepicker.css' ?>" />
<div class="input-block">
	<ul id="input-block-tabs" class="nav nav-tabs">
  		<li id="monograph" class="active">
    		<a>Монографія</a>
  		</li>
  		<li id="textbook">
  			<a>Підручник/посібник</a>
  		</li>
  		<li id="article">
  			<a>Стаття</a>
  		</li>
  		<li id="thesis">
  			<a>Тези доповідей конференції</a>
  		</li>
  		<li id="eresource">
  			<a>Електронний ресурс</a>
  		</li>
	</ul>
	<div id="monograph-content" class="content input-block center">
		<div id="monograph-author" class="hero-unit">
			<h4>Про Авторів</h4>
			<div>
				<label>Автори</label>
			</div>
			<ul id="monograph-author-list">
				<li class="author-list-template hidden">
					<span class="author-name"></span>
					<button onclick="SARM.INDEX.deleteAuthor($(this));" class="btn" type="button">-</button>
				</li>
			</ul>
			<div class="input-append">
				 <input id="author-full-name" type="text" class="span2">
			    <button id="add-button" onclick="SARM.INDEX.addAuthor();" class="btn">+</button>
			</div>
		</div>
		<div id="monograph-publication" class="hero-unit">
			<h4>Про Монографію</h4>
			<div>
				<label>Місто видавництва</label>
				<input class="input-xlarge" type="text"></input>
			</div>
			<div>
				<label>Назва видавництва</label>
				<input class="input-xlarge" type="text"></input>
			</div>
			<div>
				<label>Рік видавництва</label>
				<input id="monograph-publication-date" class="input-small" type="text"></input>
			</div>
			<div>
				<label>Кількість сторінок</label>
				<input class="input-mini" type="text"></input>
			</div>
		</div>
	</div>
	<div id="monograph-content-output" class="hero-unit right">
		<h4>Результат</h4>
		<textarea id="output-result" class="output-textarea"></textarea>
	</div>
	<div id="textbook-content" class="content input-block" style="display: none">
		<div id="textbook-author">
		</div>
		<div id="textbook-publication">
		</div>
	</div>
	<div id="article-content" class="content input-block" style="display: none">
		<div id="article-author">
		</div>
		<div id="article-publication">
		</div>
	</div>
	<div id="thesis-content" class="content input-block" style="display: none">
		<div id="thesis-author">
		</div>
		<div id="thesis-publication">
		</div>
	</div>
	<div id="eresource-content" class="content input-block" style="display: none">
		<div id="eresource-author">
		</div>
		<div id="eresource-publication">
		</div>
	</div>
</div>

